<a href="https://colab.research.google.com/github/dxdiego5/data-science-growdev-matematica-statistica/blob/main/matrizes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

matrizes 

In [2]:
import numpy as np

In [3]:
n = np.arange(1,10,1)
n

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
c = np.array([12,25,75,56])
c

array([12, 25, 75, 56])

In [ ]:
A = np.array ([[1,4,7],[4,2,-1],[7,1/2,np.sqrt(5)]])
A

In [ ]:
#  matris quadratica com identidade

In [ ]:
np_array_zero = np.zeros(10)
np_array_one = np.ones(10)
a = np.zeros(10),np.ones(10)
list(a)

In [23]:
np.zeros(shape=(10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
np.ones(shape=(10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [25]:
np.identity(10)#  matris quadratica com identidade representacao

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
# matriz inversa

In [27]:
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([[10,20,-3,5],[8,9,-7,80]])
soma = a + b
soma

array([[ -9, -18,   6,  -1],
       [ -3,  -3,  14, -72]])

In [31]:
a = np.matrix([[1,2,3,4],[5,6,7,8]])
list(a)

[matrix([[1, 2, 3, 4]]), matrix([[5, 6, 7, 8]])]

In [32]:
# calculos com matrizes
A=np.array([[2,3,8],[1,-4,0]])
C=np.array([[2,0],[8,6],[-4,-10]])
S=3*A-1/2*C.T
print(S)

[[  5.   5.  26.]
 [  3. -15.   5.]]


In [ ]:
# calculos com matrizes MULTIPLICACAO nao e comutativa

In [42]:
a = np.array([[ 1,3,2 ], [0,5,-1]])
b = np.array([[3,0],[4,-2], [1,6]])
c = a @ b
d= b @ A
c

array([[ 17,   6],
       [ 19, -16]])